package:
  name: ell
  version: !!str 0.0.1

source:
  path: .

requirements:
  build:
  - python
  run:
  - python
  - numpy
  - requests
  - paramiko
  - llvmdev >=6.0,<7.0
  - swig ==4.0.0
  - opencv
  - github

about:
  home: https://github.com/Microsoft/ELL
  license: MIT License
